server:
  prot: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming: org.hibernate.cfg.DefaultNamingStrategy
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6f34quzk4k87955o.mysql.rds.aliyuncs.com/heyong?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: heyong
    password: heyong
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp