package com.blog.utils.autoGeneration;

import java.io.IOException;
import java.sql.SQLException;
import java.util.UUID;

import freemarker.template.TemplateException;

public class AutoGenerationDemo {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
        //数据库地址
        String url = "jdbc:mysql://127.0.0.1:3306/hey";
        //用户名
        String name = "root";
        //密码
        String passWord = "root";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "sys_role";
        //模板路径
        String templateDir = "E:\\heywork\\blog\\src\\main\\java\\com\\blog\\utils\\autoGeneration";
        //生成文件路径
        String autoGeneratedFile = "E:\\heywork\\blog\\src\\main\\java\\com\\blog";
        /*for(int i=0;i<10;i++){
            String uuid = UUID.randomUUID().toString().replaceAll("-", "");
            System.out.println(uuid);
        }*/
        //System.out.println(System.getProperty("user.dir"));
        //实例化
       AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir,"jspList");
        
        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
    }

}
