package com.blog.utils.autoGeneration;

import java.io.IOException;
import java.sql.SQLException;
import java.util.UUID;

import freemarker.template.TemplateException;
import org.apache.shiro.crypto.hash.SimpleHash;
import org.apache.shiro.util.ByteSource;

public class AutoGenerationDemo {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
        //数据库地址
        String url = "jdbc:mysql://127.0.0.1:3306/hey";
        //用户名
        String name = "root";
        //密码
        String passWord = "root";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "hey_content";
        //模板路径
        //String templateDir = "E:\\heywork\\heyBlog\\src\\main\\java\\com\\blog\\utils\\autoGeneration";
        String templateDir =System.getProperty("user.dir")+"/src/main/java/com/blog/utils/autoGeneration";
        //生成文件路径
        //String autoGeneratedFile = "E:\\heywork\\heyBlog\\src\\main\\java\\com\\blog";
        String autoGeneratedFile =System.getProperty("user.dir")+"/src/main/java/com/blog";

        /*for(int i=0;i<10;i++){
            String uuid = UUID.randomUUID().toString().replaceAll("-", "");
            System.out.println(uuid);
        }*/
        //System.out.println(System.getProperty("user.dir"));
        //实例化
       AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir,"all");

        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
        //System.out.println(ByteSource.Util.bytes("admin8d78869f470951332959580424d4bf4f"));

        //System.out.println(System.getProperty("user.dir")+"/src/main/java/com/blog/utils/autoGeneration");
        /*String password= new SimpleHash("md5", // 用户名
                "123456", // 密码
                ByteSource.Util.bytes("hey6057F13C496ECF7FD777CEB9E79AE285"), // salt=username+salt
                2).toHex();

        */
    }

}
